services:
  app:
    build: .
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1